from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class TensorLike(Protocol):
    """A minimal structural type for tensor objects used by kernel wrappers.

    This is intentionally torch-free: the runtime objects are typically
    `torch.Tensor`, but we avoid importing torch for typing purposes.
    """

    shape: Any
    dtype: Any
    device: Any
    requires_grad: bool

    @property
    def ndim(self) -> int: ...

    def dim(self) -> int: ...
    def numel(self) -> int: ...
    def stride(self, dim: int) -> int: ...
    def contiguous(self) -> "TensorLike": ...
    def view(self, *shape: int) -> "TensorLike": ...
    def reshape(self, *shape: int) -> "TensorLike": ...
    def detach(self) -> "TensorLike": ...
    def to(self, *args: Any, **kwargs: Any) -> "TensorLike": ...

    def __getattr__(self, name: str) -> Any: ...

